modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/TysonTheEmber/EmbersTextAPI/issues"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="https://tysontheember.dev"
authors="${mod_authors}"
description='''${mod_description}'''
credits="TysonTheEmber"
displayTest="MATCH_VERSION"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="ftbquests"
    mandatory=false
    versionRange="*"
    ordering="NONE"
    side="CLIENT"
